#!/usr/bin/env python3
print(r''' 
######################################################################################
# ██████╗ █████╗ ██╗      ██████╗██╗   ██╗██╗      █████╗ ████████╗ ██████╗ ██████╗ ## 
#██╔════╝██╔══██╗██║     ██╔════╝██║   ██║██║     ██╔══██╗╚══██╔══╝██╔═══██╗██╔══██╗##
#██║     ███████║██║     ██║     ██║   ██║██║     ███████║   ██║   ██║   ██║██████╔╝##
#██║     ██╔══██║██║     ██║     ██║   ██║██║     ██╔══██║   ██║   ██║   ██║██╔══██╗##
#╚██████╗██║  ██║███████╗╚██████╗╚██████╔╝███████╗██║  ██║   ██║   ╚██████╔╝██║  ██║##
# ╚═════╝╚═╝  ╚═╝╚══════╝ ╚═════╝ ╚═════╝ ╚══════╝╚═╝  ╚═╝   ╚═╝    ╚═════╝ ╚═╝  ╚═╝##
#                                 press q to quit                                   ##
######################################################################################
''')

while True:
    number1 = float(input("type your first number "))
    number2 = float(input("type your second number "))
    opreation = input("type your desired opereation / * + - ")

    if opreation == "-":
        opm = (number1 - number2)
        print(opm)
    elif opreation == "+":
        opp = (number1 + number2)
        print(opp)
    elif opreation == "*":
        op = (number1 * number2)
        print(op)
    elif opreation == " ":
        print("no opreation spesified")
    elif opreation == "":
        print("no opreation spesified")
    elif opreation == "/":
        if number2 == 0:
            print("dividing by 0 is undefined")
        else:
            opd = number1 / number2
            print(opd)
    elif opreation == "q":
        break
    elif number1 == "q":
        break
    elif number2 == "q":
        break
